services:
  useflow-fr-addon:
    build: .
    container_name: useflow-fr
    restart: always
    ports:
      - "7973:7000"
    volumes:
      - /home/aerya/docker/useflow-fr/data:/data
    environment:
      - PORT=7000
      - NODE_ENV=production
      - WEBUI_USERNAME=admin
      - WEBUI_PASSWORD=admin
      - DB_PATH=/data/addon.db
      - SESSION_SECRET=278f898a4fdbecc8cfd904646336d08a32c04afdad664bacdfc5b8334dfb6653 # à générer avec openssl rand -hex 32
